services:
  # node:
  #   container_name: node
  #   build: ./back-end
  #   ports:
  #     - 5000:5000
  #   env_file:
  #     - ./back-end/.env
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./backend/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  # react:
  #   container_name: react
  #   build: ./front-end
  #   volumes:
  #     - react-volume:/var/www/html

  # nginx:
  #   container_name: nginx_container
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - react-volume:/var/www/html
  #   depends_on:
  #     - node
  #     - react

volumes:
  postgres-volume:
  # react-volume:
